Add an optinal second network interface
rapido-linux/rapido pull request #143
Opened 2020-10-19 16:28 UTC by scabrero

Changes:

* Rename configuration variables to use `BRx_` and `VMx_` as prefix
* Allow to skip the bridge device provision with `BRx_DEV_SKIP_PROVISION`, useful to reuse the bridge devices created by libvirt and connect the rapido VMs to them
* Allow to create a second network adapter in each VM, connected to the second bridge device `BR2_DEV`.
* Setup the network in `vm_autorun.env` instead of using the `ip=` kernel parameter. It will allow to use IPv6 addresses in the future.

2020-10-20 11:19 UTC, ddiss requested changes
Thanks a lot for your changes here, Samuel.

Aside from the minor inline comments I have two concerns regarding the approach:
- although very helpful for some use-cases, I'm worried about the configuration complexity added for new users here.
  + perhaps we could reuse some other existing config syntax (sysconfig ifcfg or dnsmasq) so that users don't need to learn something new, and we don't need to continuously to add new rapido.conf options
  + I raised this approach a while back via https://github.com/rapido-linux/rapido/issues/89
- this will break users' with existing rapido.conf network configs, requiring them to rewrite them.
  + I don't want to support old and new syntax, but maybe some sort of upgrade helper would be worth while?
- moving from kernel dhcp client to `dhclient` seem like a good idea (finally we can support standard distro kernels), but it does appear to add a little bit of bloat to images

2020-10-20 11:19 UTC, ddiss commented on tools/br_setup.sh
>  fi
Instead of adding the `BR1_DEV_SKIP_PROVISON` param, could we just ignore any preexisting bridge interface here?

2020-10-29 13:03 UTC, ddiss commented
> Thanks a lot for your changes here, Samuel.
> 
> Aside from the minor inline comments I have some concerns regarding the approach:
> 
>     * although very helpful for some use-cases, I'm worried about the configuration complexity added for new users here.
>       
>       * perhaps we could reuse some other existing config syntax (sysconfig ifcfg or dnsmasq) so that users don't need to learn something new, and we don't need to continuously to add new rapido.conf options
>       * I raised this approach a while back via #89
> 
>     * this will break users' with existing rapido.conf network configs, requiring them to rewrite them.
>       
>       * I don't want to support old and new syntax, but maybe some sort of upgrade helper would be worth while?
> 
>     * moving from kernel dhcp client to `dhclient` seem like a good idea (finally we can support standard distro kernels), but it does appear to add a little bit of bloat to images

@scabrero any thoughts on how you think we should proceed here?

2020-10-30 13:13 UTC, scabrero commented on tools/br_setup.sh
>  fi
This is a good idea. I will change it.

2020-10-30 13:21 UTC, scabrero commented
> > Thanks a lot for your changes here, Samuel.
> > Aside from the minor inline comments I have some concerns regarding the approach:
> > ```
> > * although very helpful for some use-cases, I'm worried about the configuration complexity added for new users here.
> >   
> >   * perhaps we could reuse some other existing config syntax (sysconfig ifcfg or dnsmasq) so that users don't need to learn something new, and we don't need to continuously to add new rapido.conf options
> >   * I raised this approach a while back via #89
> > 
> > * this will break users' with existing rapido.conf network configs, requiring them to rewrite them.
> >   
> >   * I don't want to support old and new syntax, but maybe some sort of upgrade helper would be worth while?
> > 
> > * moving from kernel dhcp client to `dhclient` seem like a good idea (finally we can support standard distro kernels), but it does appear to add a little bit of bloat to images
> > ```
> 
> @scabrero any thoughts on how you think we should proceed here?

I had a look to #89 and I am wondering, what do you think if we add systemd and systemd-networkd to all images and provide the systemd-networkd files for each vm in `rapido-net-conf/vmX/`, injecting them into the initramfs image using DRACUT_RAPIDO_INCLUDES?

We could extend it and install systemd-resolved too to have DNS resolution in the VMs.

2020-10-30 14:03 UTC, ddiss commented
> I had a look to #89 and I am wondering, what do you think if we add systemd and systemd-networkd to all images and provide the systemd-networkd files for each vm in rapido-net-conf/vmX/, injecting them into the initramfs image using DRACUT_RAPIDO_INCLUDES?

I'd like to keep dependencies/images minimal, so using systemd-networkd only would be my preference if possible (it's under 500k and appears to be quite powerful). I had a play with it myself, but couldn't get it to bring up a dhcp client address by itself. In the end all I really want is an clean network config syntax which could be used for configuring an arbitrary number of NICs per-VM, with static or dhcp based v4 or v6 addresses, etc., preferably outside of rapido.conf .

2021-04-22 08:13 UTC, ddiss commented
> I'd like to keep dependencies/images minimal, so using systemd-networkd only would be my preference if possible (it's under 500k and appears to be quite powerful). I had a play with it myself, but couldn't get it to bring up a dhcp client address by itself. In the end all I really want is an clean network config syntax which could be used for configuring an arbitrary number of NICs per-VM, with static or dhcp based v4 or v6 addresses, etc., preferably outside of rapido.conf .

Just an update here - I plan on retesting with an updated systemd-networkd once I upgrade to openSUSE 15.3. @scabrero given that you had systemd-networkd working standalone on Tumbleweed, I'm hoping it's just the newer version that's needed before we can merge here.

2022-01-17 13:25 UTC, ddiss commented
> Just an update here - I plan on retesting with an updated systemd-networkd once I upgrade to openSUSE 15.3. @scabrero given that you had systemd-networkd working standalone on Tumbleweed, I'm hoping it's just the newer version that's needed before we can merge here.

The systemd-networkd approach tracked via https://github.com/rapido-linux/rapido/pull/147 seems to be progressing quite well, and should offer a cleaner and more flexible configuration format supporting multihoming. @scabrero I'm going to close this, but feel free to reopen if you feel strongly about keeping these changes.

2022-01-17 13:25 UTC, closed without merging