WIP Use systemd-networkd to configure the network
rapido-linux/rapido pull request #147
Opened 2020-12-15 10:41 UTC by scabrero

Remaining issues and possible solutions:

- Drop IP_ADDR1 and IP_ADDR2 references in autorun scripts
  Get the address from the interface at run time

- Fix br_setup static DHCP leases
  Redefine the IP_ADDR1_DHCP variable to be the static lease address instead a boolean.

- Remove IP_ADDR1, IP_ADDR2, IP_ADDR1_DHCP and IP_ADDR2_DHCP variables

2020-12-15 10:58 UTC, ddiss commented on net-conf/20-vm1-eth0.network
> +KernelCommandLine=rapido.vm_num=1
I wasn't aware of this functionality - nice!

2020-12-15 10:58 UTC, ddiss commented on runtime.vars
> +				--modules dracut-systemd"
Adding systemd to all images is going to be quite a hit WRT image size (and likely boot time). I'd hoped that we could run the systemd-networkd binary independently if possible. Also, ideally we only need it for images that require network (i.e. without `_rt_xattr_vm_networkless_set`).

2020-12-15 11:27 UTC, ddiss commented on cut/mpath_local.sh
> +	--modules "multipath" \
does dracut support multiple `--modules` parameters? I think I'd prefer to use `--modules "$DRACUT_RAPIDO_MODULES multipath"` instead if you're okay with it.
It's inconsistent with `$DRACUT_RAPIDO_INCLUDES`, but double-param `--include` arguments are a special case.

2020-12-15 12:11 UTC, ddiss commented on cut/mpath_local.sh
> +	--modules "multipath" \
> I think I'd prefer to use --modules "$DRACUT_RAPIDO_MODULES multipath" instead if you're okay with it.

...or just keep it as-is if we can get away without the new modules (and instead just add the systemd-networkd binary).

2020-12-15 12:18 UTC, scabrero commented on cut/mpath_local.sh
> +	--modules "multipath" \
Yes, it supports multiple --modules parameters. Ok, I will change it.

2020-12-15 12:19 UTC, scabrero commented on runtime.vars
> +				--modules dracut-systemd"
I tried adding the binary and it works. I will push an update without adding these modules.

2020-12-15 14:30 UTC, ddiss requested changes
This looks like it's almost ready. A couple of things I'd still like to look at:
- documentation should be updated for this new network setup
- we should probably provide a helper to migrate existing rapido.conf IPs to the new config
- some feedback from other rapido users would be nice
  - @luis-henrix can you live with this (minimal) use of `systemd-networkd`? I think it puts us in a better position for supporting more complex network setups, while avoiding extra cludge in rapido.conf . Dropping kernel `ip=` for assignment means we could also finally move towards supporting regular distro kernels (with `KERNEL_SRC` commented out).

Thanks a lot Samuel!

2020-12-15 14:30 UTC, ddiss commented on runtime.vars
> +	DRACUT_RAPIDO_INSTALLS="nohup /usr/lib/systemd/systemd-networkd"
I'd like to only have this installed for images that don't flag themselves as networkless via `_rt_xattr_vm_networkless_set`. Given that networkless is only flagged after image generation, I think for now we should just set:
`DRACUT_RAPIDO_INSTALLS_NET="nohup /usr/lib/systemd/systemd-networkd ip ping"`

and only add `$DRACUT_RAPIDO_INSTALLS_NET` to the `--install` list for images that don't flag themselves networkless.

Alternatively we could add a `_rt_require_dracut_args_networkless` wrapper alongside  `_rt_require_dracut_args` and conditionally set `$DRACUT_RAPIDO_INSTALLS`.

2020-12-15 14:33 UTC, ddiss commented on runtime.vars
> +	DRACUT_RAPIDO_INSTALLS="nohup /usr/lib/systemd/systemd-networkd"
Thinking about this more, I think the `_rt_require_dracut_args_networkless` wrapper would probably be my preference here.

2020-12-16 10:24 UTC, scabrero commented on runtime.vars
> +	DRACUT_RAPIDO_INSTALLS="nohup /usr/lib/systemd/systemd-networkd"
Done

2020-12-16 10:25 UTC, scabrero commented on vm_autorun.env
> +nohup /usr/lib/systemd/systemd-networkd &
Done

2020-12-16 10:35 UTC, scabrero commented on vm.sh
>  		qemu_netdev="-net none"	# override default (-net nic -net user)
Done

2020-12-16 10:35 UTC, scabrero commented on vm.sh
>  	else
Done

2020-12-16 12:10 UTC, scabrero commented
Removing IP_ADDR1 and IP_ADDR2 from autorun scripts won't be so easy as get the address from the interface. The ctdb_cephfs.sh script for example needs both to generate the CTDB nodes file.

2022-01-14 17:43 UTC, ddiss commented
@scabrero I'm revisiting your work here, as I need more than two networked VMs for some ldap+automount test cases that I'm running. With openSUSE Leap 15.3 I'm able to run systemd-networkd standalone and it appears to handle static and dhcp configured interfaces quite nicely, along with MAC settings, etc. :partying_face:

I plan on doing more bloat measurements / benchmarks before taking this further, especially given the change in config syntax. I'd hoped that we could additionally use systemd-network configuration for host-side bridge and tap devices, but I haven't yet found a way how we can do that cleanly.

2022-02-16 12:31 UTC, ddiss commented
https://github.com/rapido-linux/rapido/pull/173 is a continuation of this PR, so I'm going to close this.

2022-02-16 12:31 UTC, closed without merging