WIP: rapido: add fstests-btrfs-zoned cut script
rapido-linux/rapido pull request #151
Opened 2021-02-09 15:08 UTC by morbidrsa

Work in Progress!!!!

Add support for running fastest with btrfs on zoned null_blk devices.

Upstream btrfs has not yet merged zoned support (only staged in a separate branch) and user-space utilities are not update upstream either. But we have been using this cut script for about one year assisting our development of the patches.

2021-02-09 17:10 UTC, ddiss requested changes
Aside from the changes mentioned, this looks okay. If it relies on out of tree kernel functionality, then please link to the patchset (repo or mailing list URL) at the top of the cut script.

2021-02-09 17:10 UTC, ddiss commented on cut/fstests_btrfs_zoned.sh
> +_rt_require_dracut_args
With the new boot/init path, this should be:
```
_rt_require_dracut_args "$RAPIDO_DIR/autorun/fstests_btrfs_zoned.sh" "$@"
```

2021-02-09 17:10 UTC, ddiss commented on autorun/fstests_btrfs_zoned.sh
> +. /vm_autorun.env
the `/vm_autorun.env` check and source above should be replaced with `_vm_ar_env_check || exit 1`

2021-02-09 17:16 UTC, morbidrsa commented on autorun/fstests_btrfs_zoned.sh
> +mount -t $filesystem /dev/nullb0 /mnt/test #|| _fatal
Yes and no. A null_blk device can be memory backed as well and then it acts like a Ramdisk.

2021-02-09 17:18 UTC, morbidrsa commented
> Aside from the changes mentioned, this looks okay. If it relies on out of tree kernel functionality, then please link to the patchset (repo or mailing list URL) at the top of the cut script.

I'd prefer not getting it merged until it is in Linus' tree (for the kernel side) and btrfs-progs, but wanted to have your feedback on it.

2021-02-09 17:35 UTC, ddiss commented
> > Aside from the changes mentioned, this looks okay. If it relies on out of tree kernel functionality, then please link to the patchset (repo or mailing list URL) at the top of the cut script.
> 
> I'd prefer not getting it merged until it is in Linus' tree (for the kernel side) and btrfs-progs, but wanted to have your feedback on it.

Sure, works for me, I'm fine with queuing it up here until it reaches mainline.

2021-02-09 17:37 UTC, ddiss commented on autorun/fstests_btrfs_zoned.sh
> +mount -t $filesystem /dev/nullb0 /mnt/test #|| _fatal
> Yes and no. A null_blk device can be memory backed as well and then it acts like a Ramdisk.

Okay, in that case I'm curious how it differs from zram with compression disabled... Either way I'm fine with this as is, although please uncomment the mount `|| _fatal` error path.

2021-02-09 17:44 UTC, morbidrsa commented on autorun/fstests_btrfs_zoned.sh
> +mount -t $filesystem /dev/nullb0 /mnt/test #|| _fatal
> Okay, in that case I'm curious how it differs from zram with compression disabled... 
That's easy to answer, zram is a bio based driver, whereas null_blk is configurable to be either a bio or a blk-mq based driver. Also null_blk can emulate a zoned block device, which is why we need to use it and can't use zram.

2021-02-11 12:42 UTC, ddiss approved these changes
Looks fine. Let's merge this when the kernel changes reach mainline.

2021-02-11 13:22 UTC, morbidrsa commented
> Looks fine. Let's merge this when the kernel changes reach mainline.

Yep it's in misc-next so after the merge window ends we should be good to go

2021-04-28 11:09 UTC, morbidrsa commented
v5.12 is out, so I think we can pull it in. Please mind that the user-space side of things still isn't 100% merged.

2021-04-28 11:53 UTC, ddiss commented
Thanks for the update. I'll merge this today after I take a final look at it.

2021-04-28 13:04 UTC, merged