rdma: use the rdma tool
rapido-linux/rapido pull request #174
Opened 2022-01-30 09:42 UTC by x2c3z4

The 5.17-rcX kernel[1] has removed the module parameters, so
have to use the 'rdma' tool.

[1]: https://www.spinics.net/lists/linux-rdma/msg108004.html

Signed-off-by: Li Feng <fengli@smartx.com>

2022-01-30 22:42 UTC, ddiss requested changes

2022-01-30 22:42 UTC, ddiss commented on autorun/nvme_rdma.sh
> +fi
Thanks a lot for the pull request!
Given that `rdma` should now always be present, can't we use it unconditionally here? Also, please call `_fatal` on error here.

2022-02-12 09:07 UTC, x2c3z4 commented on autorun/nvme_rdma.sh
> +fi
Done.

2022-02-14 08:58 UTC, ddiss approved these changes
merging now, thanks!

2022-02-14 08:58 UTC, merged