LTP small improvements
rapido-linux/rapido pull request #190
Opened 2022-10-24 14:26 UTC by pevik

* cut/ltp.sh: Add more tools
* ltp: Use SPDX
* autorun/ltp.sh: cd to LTP tests directory
* autorun/ltp.sh: export LTPROOT

2022-10-24 18:56 UTC, ddiss requested changes

2022-10-24 18:56 UTC, ddiss commented on cut/ltp.sh
> +		mktemp $(ls /sbin/mount*) od parted \
Thanks a lot for the submission, Petr!
The changes look fine, but I'd prefer to avoid these wildcards, just in case someone has a private `/sbin/mount-my-hdd-with-luks-password` script or something.
My preference would be something like:
```
fses=(btrfs ext2 ext3 ext4 ...)
dracut --install "... ${fses[*]/#/mount.} ${fses[*]/#/mkfs.} ..."
```

2022-10-25 10:17 UTC, pevik commented on cut/ltp.sh
> +		mktemp $(ls /sbin/mount*) od parted \
If you're ok, that I'll include `fuse`, there is only `mount.fuse`, but not `mkfs.fuse`, thus extra error will be produced.

2022-10-25 11:49 UTC, pevik commented
@ddiss  I'm sorry for many changes, fixed few problems. Could you please have a second look?

2022-10-30 22:24 UTC, ddiss commented on cut/ltp.sh
> +		mktemp $(ls /sbin/mount*) od parted \
good point. in that case I think it'd make sense to go back to listing them all separately, without globbing (sorry for the run-around).

2022-10-30 22:26 UTC, ddiss commented on cut/ltp.sh
> -		${LTP_DIR}/bin/* ${LTP_DIR}/testcases/bin/*" \
why did you drop the `LTP_DIR/...` installs? They're likely still needed for pulling in the shared object dependencies. IIRC, we discussed this with the initial merge.

2022-10-31 16:20 UTC, pevik commented on cut/ltp.sh
> -		${LTP_DIR}/bin/* ${LTP_DIR}/testcases/bin/*" \
I guess you're talking about https://github.com/rapido-linux/rapido/pull/85#discussion_r280192054. You were discussing libraries. There are no shared libraries, there are only statically linked libraries:

```
$ find libs/ |grep -e '\.so$' -e '\.a'
libs/libltpipc/libltpipc.a
libs/libltpnewipc/libltpnewipc.a
libs/libltpnuma/libltpnuma.a
libs/libltpsigwait/libltpsigwait.a
libs/libltpswap/libltpswap.a
libs/libltpuinput/libltpuinput.a
libs/libltpvdso/libltpvdso.a
```

Everything installed in `/opt/ltp/testcases/bin` is included with the current setup. Testing `rt_sigtimedwait01`, which uses `libs/libltpsigwait/libltpsigwait.a` and it works with current setup. `msgctl01` which uses `libs/libltpnewipc/libltpnewipc.a` and it also works. And the reason is really that everything is statically compiled.

There are very few dynamic library dependencies used for 0.5% of LTP tests - e.g. libmnl-devel
But with the current setup it works in initramfs:
```
# ldd ./route-change-netlink | grep -i libmnl
        libmnl.so.0 => /usr/lib64/libmnl.so.0 (0x00007f9b26b2f000)
```
Therefore I'd suggest to keep it. But if you insist to keep it, I'll put it back.

2022-11-07 21:44 UTC, ddiss commented on cut/ltp.sh
> -		${LTP_DIR}/bin/* ${LTP_DIR}/testcases/bin/*" \
> I guess you're talking about [#85 (comment)](https://github.com/rapido-linux/rapido/pull/85#discussion_r280192054). You were discussing libraries.

That's the one :-)
...
> There are very few dynamic library dependencies used for 0.5% of LTP tests - e.g. libmnl-devel But with the current setup it works in initramfs:
> 
> ```
> # ldd ./route-change-netlink | grep -i libmnl
>         libmnl.so.0 => /usr/lib64/libmnl.so.0 (0x00007f9b26b2f000)
> ```

These sorts of LTP-external library dependencies are what I'm concerned about. FWIW, `cut/ltp.sh` carries `--install ip`, which is why Dracut pulls in `libmnl.so.0` automatically.

> Therefore I'd suggest to remove `${LTP_DIR}/bin/* ${LTP_DIR}/testcases/bin/*` (as it's in the current code). But if you insist to keep it, I'll put it back. Or give me an example what else could be "shared object dependency".

Even if LTP has very few external dependencies, I'd still prefer to keep using the `dracut --install` shared-object dependency checks to pull in what's needed.

2022-11-07 23:05 UTC, pevik commented on cut/ltp.sh
> -		${LTP_DIR}/bin/* ${LTP_DIR}/testcases/bin/*" \
OK, replaced with commit, which added just directories into `$PATH`.

2022-11-07 23:30 UTC, ddiss approved these changes

2022-11-07 23:43 UTC, merged