Add net test
rapido-linux/rapido pull request #230
Opened 2023-12-09 05:13 UTC by acooks

Thank you for creating and maintaining rapido!

It's been really useful for testing a network device driver I'm working on and I would like to share the changes I've made.

2023-12-10 14:47 UTC, pevik commented on rapido.conf.example-net_test
> +KERNEL_SRC="/home/acooks/linux/"
I suppose @ddiss will give more feedback. But this is certainly wrong.

2023-12-10 14:48 UTC, pevik commented on rapido.conf.example-net_test
> +
Why so many blank lines?

2023-12-10 14:52 UTC, pevik commented on rapido.conf.example-net_test
> +# Path to Linux kernel source. Prior to running "rapido cut", the kernel
Copy paste whole `rapido.conf.example` with minimal changes looks wrong to me. Why not just add new section to it?

2023-12-10 20:50 UTC, acooks commented on rapido.conf.example-net_test
> +# Path to Linux kernel source. Prior to running "rapido cut", the kernel
I added a complete working example config to show exactly how I'm using the software.

It is meant to help you, the reviewer understand how many things need to be configured and how, because it's not entirely obvious what variables need to be configured and how, when given only the four new variables by themselves.

It is clearly not ready to merge as is, and I was hoping a reviewer would understand the complexity issue and set a direction fixing it. Perhaps there is some value in providing more example config files that show all variables that are relevant to a particular use case and none of the other varables.

How would you proivde the user instructions and avoid adding complexity into the example config?

2023-12-11 01:01 UTC, ddiss commented
Thanks for the PR!
As @pevik indicated, this appears to add quite a bit of extra complexity to rapido.conf. Hopefully some of it can be avoided by reworking the changes a little:
* your use case appears to target tn40xx-driver development, so I think it'd be nice to have tn40xx specific cut/autorun scripts instead of generic net-test
  * `cut/tn40xx` could then pull in the driver and test suite from e.g. `TN40XX_DRIVER_SRC`
  * `autorun/tn40xx` could run `start.sh` directly, or let users run it (with flexible parameters) via `rapido cut -x "./start.sh ..." tn40xx` 
* `rapido.conf` is included by VMs on boot, so the `QEMU_EXTRA_KERNEL_PARAMS` changes shouldn't be needed
  * ideally `NET_TEST_DEV_VM` could also be assumed / autodetected by `autorun/tn40xx`
* I appreciate that you've put together a standalone example config for your use case. I think it would be best suited to live under e.g. `docs/tn40xx_guide.md` similar to the Ceph guide

I'll add a few other minor style comments inline...

2023-12-11 01:21 UTC, ddiss requested changes

2023-12-11 01:21 UTC, ddiss commented on cut/net_test.sh
> +	ping \
please put these after `--install` directly, rather than using a separate variable.

2023-12-11 01:21 UTC, ddiss commented on cut/net_test.sh
> +  _fail "specify a kernel module to test in rapido.conf"
`[[ -n $NET_TEST_KMOD ]]` should work fine for this, but as mentioned, hopefully this can be hardcoded as a tn40xx specific kernel module.

2023-12-11 01:21 UTC, ddiss commented on cut/net_test.sh
> +	--include "${NET_TEST_SUITE}" "driver-tests" \
If possible, please use the same host source and VM destination paths. The reason for doing so is that `dracut --install` can then also be used to pull in any additional shared object dependencies; `dracut --install <bin>` parses `ldd <bin>` output for dependencies while `dracut --include` ignores it.

2023-12-11 02:31 UTC, acooks commented
Thank you for the quick review and feedback!

>     * your use case appears to target tn40xx-driver development, so I think it'd be nice to have tn40xx specific cut/autorun scripts instead of generic net-test
>       

Are you sure you'd want to be so specific about the driver?

I started from the very specific case, but thought it was too specific to upstream, because it wouldn't be useful to anyone else. However, the generic case for testing drivers for passed-through devices seems like more than just a once-off need.

For example, it might also be useful for these similar out-of-mainline network drivers:
https://github.com/morrownr/8814au
https://github.com/Mange/rtl8192eu-linux-driver/
https://github.com/lwfinger/rtl8192du

The goal for these drivers is probably to cease stand-alone development and be superseded by a mainline driver, but even then, the rapido developer workflow that enables passing the peripheral and driver into a VM is so much better than any of the alternatives I've seen (and not specific to network devices, or pci devices, or even device drivers).

2023-12-11 02:47 UTC, acooks commented on cut/net_test.sh
> +	--include "${NET_TEST_SUITE}" "driver-tests" \
It's great that dracut is smart enough to do that.  I figured I'd put all the standard utilities with discoverable shared object dependencies in the install parameter, and create a conventional place to put the custom test suite, which may have non-discoverable shared objects and unknowable other cruft.

2023-12-11 03:46 UTC, ddiss commented
> Thank you for the quick review and feedback!

No worries :-)

> > ```
> > * your use case appears to target tn40xx-driver development, so I think it'd be nice to have tn40xx specific cut/autorun scripts instead of generic net-test
> > ```
> 
> Are you sure you'd want to be so specific about the driver?
> 
> I started from the very specific case, but thought it was too specific to upstream, because it wouldn't be useful to anyone else. However, the generic case for testing drivers for passed-through devices seems like more than just a once-off need.
> 
> For example, it might also be useful for these similar out-of-mainline network drivers: https://github.com/morrownr/8814au https://github.com/Mange/rtl8192eu-linux-driver/ https://github.com/lwfinger/rtl8192du

Understood. Given that the test environment, kernel module and test suite currently appear to be tn40xx specific, I think it still makes sense to keep it separate for now. Similar future (e.g. rtlX) network driver environments could reuse your scripts where needed (e.g. via `autorun/lib/`). 

> The goal for these drivers is probably to cease stand-alone development and be superseded by a mainline driver, but even then, the rapido developer workflow that enables passing the peripheral and driver into a VM is so much better than any of the alternatives I've seen (and not specific to network devices, or pci devices, or even device drivers).

Sounds like a worthy goal. Glad to hear that the rapido workflow is useful for others.

2023-12-15 07:02 UTC, ddiss commented
Thanks for the update, but this doesn't appear to address many of the previous comments:
* please rename it to match the specific functionality/driver to be tested, e.g. `cut/tn40xx.sh` and `autorun/tn40xx.sh`
* avoid adding new rapido.conf variables where possible
  * hardcode `NET_TEST_KMOD` as `tn40xx`
  * add a `TN40XX_DRIVER_SRC` variable, which is used instead of `NET_TEST_SUITE`
  * drop `NET_TEST_DEV_HOST`
    * instead you could check that `QEMU_EXTRA_ARGS` includes a `vfio-pci` device, similar to what we do in `cut/ocfs2.sh`
  * drop `NET_TEST_DEV_VM`: can this be hardcoded or discovered in the autorun script?

```
+       --include "${KERNEL_SRC}/samples/pktgen" "pktgen" \
+       --include "${NET_TEST_SUITE}" "driver-tests" \
```
Please use the host path in the VM:
```
+       --include "${KERNEL_SRC}/samples/pktgen" "${KERNEL_SRC}/samples/pktgen" \
+       --include "${TN40XX_DRIVER_SRC}/test" "${TN40XX_DRIVER_SRC}/test" \
```

```
+/driver-tests/start.sh ${NET_TEST_DEV_VM} ${NET_TEST_KMOD}
```
Depending on whether you think you'll only ever be running `start.sh`, you might want the autorun script to just have:
```
cd ${TN40XX_DRIVER_SRC}/test
```

you could then trigger the script via `./rapido cut -x "./start.sh DEV tn40xx" tn40xx`

2023-12-15 08:11 UTC, closed without merging

2023-12-15 08:11 UTC, acooks commented
> Thanks for the update, but this doesn't appear to address many of the previous comments:
> 
>     * please rename it to match the specific functionality/driver to be tested, e.g. `cut/tn40xx.sh` and `autorun/tn40xx.sh`
> 
>     * avoid adding new rapido.conf variables where possible
>       
>       * hardcode `NET_TEST_KMOD` as `tn40xx`
>       * add a `TN40XX_DRIVER_SRC` variable, which is used instead of `NET_TEST_SUITE`
>       * drop `NET_TEST_DEV_HOST`
>         
>         * instead you could check that `QEMU_EXTRA_ARGS` includes a `vfio-pci` device, similar to what we do in `cut/ocfs2.sh`
>       * drop `NET_TEST_DEV_VM`: can this be hardcoded or discovered in the autorun script?
> 
> 
> ```
> +       --include "${KERNEL_SRC}/samples/pktgen" "pktgen" \
> +       --include "${NET_TEST_SUITE}" "driver-tests" \
> ```
> 
> Please use the host path in the VM:
> 
> ```
> +       --include "${KERNEL_SRC}/samples/pktgen" "${KERNEL_SRC}/samples/pktgen" \
> +       --include "${TN40XX_DRIVER_SRC}/test" "${TN40XX_DRIVER_SRC}/test" \
> ```
> 
> ```
> +/driver-tests/start.sh ${NET_TEST_DEV_VM} ${NET_TEST_KMOD}
> ```
> 
> Depending on whether you think you'll only ever be running `start.sh`, you might want the autorun script to just have:
> 
> ```
> cd ${TN40XX_DRIVER_SRC}/test
> ```
> 
> you could then trigger the script via `./rapido cut -x "./start.sh DEV tn40xx" tn40xx`

Thank you for the feedback. It's clear enough what you expect and I am still trying to incorporate it, but I'm not yet able to see a way to implement it in such a way that this software does what I need it to do.

With the changes in the PR I was able to do basic network device driver tests, like:
* loading and unloading the kernel module,
* setting the network interface up and down,
* changing MTU

These tests are obviously still quite basic and immature, but I couldn't find an existing reusable test suite and I need it, so I guess I'm building something.

The next tests I need to write will have to send and receive some actual network traffic and to do that, I'm working towards spinning up multiple VMs, passing a different PCI device with its appropriate driver to each VM from the host, and running the appropriate scripts to support support the test.

And that work will be balanced with working on the actual tn40xx driver.

I'll close this PR for now and perhaps try again when I have a better idea of how to get to an acceptable solution that still meets my needs.

Thanks again!

2023-12-15 13:22 UTC, ddiss commented
...
> Thank you for the feedback. It's clear enough what you expect and I am still trying to incorporate it, but I'm not yet able to see a way to implement it in such a way that this software does what I need it to do.
> 
> With the changes in the PR I was able to do basic network device driver tests, like:
> 
>     * loading and unloading the kernel module,
> 
>     * setting the network interface up and down,
> 
>     * changing MTU
> 
> 
> These tests are obviously still quite basic and immature, but I couldn't find an existing reusable test suite and I need it, so I guess I'm building something.
> 
> The next tests I need to write will have to send and receive some actual network traffic and to do that, I'm working towards spinning up multiple VMs, passing a different PCI device with its appropriate driver to each VM from the host, and running the appropriate scripts to support support the test.

Sounds good Andrew. FWIW, I'd still very much like to carry your changes upstream. I'd just prefer to keep things relatively self-contained and non-generic.

> And that work will be balanced with working on the actual tn40xx driver.
> 
> I'll close this PR for now and perhaps try again when I have a better idea of how to get to an acceptable solution that still meets my needs.

Please do try to resubmit when you have something somewhat self-contained that you're happy with.